Invoke-Command Serv1 {New-NetFirewallRule -DisplayName "Block Ping" -Action Block -Direction
 Inbound -Protocol "ICMPV4"}
# requires -module PSLib
[CmdletBinding()]
Param(
    [Parameter(ValueFromPipeline=$true)]
    [string[]]$computerName = "localhost",
    [string]$reportDir = "C;\Reports"
)
Begin{
    if(-not (Test-Path $reportDir)){
        New-Item -Path $reportDir -ItemType Directory
    }
}

$style = @"
<style>
body {
    font-size: 10pt;
    margin: 10px
}
</style>
"@

Process {
    foreach ($computer in $computerName) {
        if(-not (Test-Net -computerName $computer).Reachable) {
            $properties = @{
                computer = $computer
                status = "OFFLINE"
            }
            $result = New-Object -TypeName psobject -Property $properties
        }Else {
            $result = Get-Service -ComputerName $computer | Select-Object ServiceName, DisplayName, StartType, Status
        }
        $result | ConvertTo-Html -Title "Windows Services: $computer" -Body (Get-Date)
         -Head $style -Pre "<p>Generated by Corporate IT </p>"
         Out-File (Join-Path -Path $reportDir -ChildPath "$computer.html")
    }
}

