---
- name: Install Grafana 
  hosts: all 
  become: yes 

  tasks: 
    - name: Download apt key 
      anisble.builtin.apt.key:
        url: https://packages.grafana.com/gpg.key
        state: present 
    - name: Add Grafana Repo 
      ansible.builtin.apt_repository:
        repo: deb https://packages.grafana.com/oss.deb stable main 
        state: present 
    - name: Update Apt Cache and Install Grafana
      anisble.builtin.apt:
        name: grafana 
        update_cache: yes 
    - name: Ensure Grafana is Started and Enabled 
      ansible.builtin.systemd: 
        name: grafana-server
        enabled: yes 
        state: started
    